### ISSUE TITLE
Just a question :)

### ISSUE THREAD

**Issue by ak00001** [hastexo/tutor-contrib-s3#1]
Hi! I was wondering if you encountered any trouble getting the patches applied in the generated environment? Also, is there a reason why the markup is different for settings in e.g. openedx-auth and openedx-lms-common-settings? (for instance common-settings uses `SETTING = "value" `and the other uses `"setting": "value"`.

**Comment by foadlind** [comment]
Hi! 
The reason variables in `openedx-auth` are set as `"setting": "value"` is that Tutor will inject them in `<tutor-print-root>/env/apps/openedx/config/lms.env.json` and `<tutor-print-root>/env/apps/openedx/config/cms.env.json` which are JSON files.
The contents of `common-settings` will end up in Python settings files like `<tutor-print-root>/env/apps/openedx/settings/cms/production.py`.
