### ISSUE TITLE
extra bucket name in the request url

### ISSUE THREAD

**Issue by vunguyen-dmt** [hastexo/tutor-contrib-s3#22]
Normally a request looks something like this: {bucket_name}.s3.amazonaws.com/submissions_attachments.
But in my case it looks like this: {bucket_name}.s3.amazonaws.com/**{bucket_name}**/submissions_attachments

I use this for AWS S3 and my setting is:
OPENEDX_AWS_ACCESS_KEY=my_key
OPENEDX_AWS_SECRET_ACCESS_KEY_my_secret
S3_HOST={my_bucket_name}.s3.amazonaws.com
S3_REGION=ap-southeast-1
S3_PORT=80
S3_USE_SSL=false
S3_STORAGE_BUCKET={my_bucket_name}

**Comment by fghaas** [comment]
In your case there should actually be no need to override `S3_HOST` at all. It already defaults to `s3.amazonaws.com`, and the bucket name prefix should be handled by `S3_ADDRESSING_STYLE: virtual`, which is also the default (`virtual` is virtual-host bucket addressing, `path` is the legacy path style).

Please let us know if that helps!

**Comment by vunguyen-dmt** [comment]
@fghaas thank you for the quick response.
I tried a new  config like this:
OPENEDX_AWS_ACCESS_KEY=my_key
OPENEDX_AWS_SECRET_ACCESS_KEY_my_secret
S3_REGION=ap-southeast-1
S3_PORT=80
S3_USE_SSL=false
S3_STORAGE_BUCKET={my_bucket_name}

When I upload ORA file it give me a url like this: http://s3.amazonaws.com/{my_bucket_name}/submissions_attachments/
which doesn't work.
The right url should look like  this: {bucket_name}.s3.amazonaws.com/submissions_attachments

**Comment by fghaas** [comment]
@foadlind, would you mind taking a look at this?

@vunguyen-dmt Out of curiosity, do things work better for you if you use the `path` addressing style? (Also, is there a particular reason why you're disabling HTTPS?)

**Comment by vunguyen-dmt** [comment]
@fghaas S3_ADDRESSING_STYLE=path doesn't work as well. I use http because my dev server doesn't have SSL and some components like ORA will not load if I config storage to S3. I  will probably use https on my production server.

**Comment by foadlind** [comment]
@vunguyen-dmt the fix for this (#23) is now merged. 
Your config should then be:
```
OPENEDX_AWS_ACCESS_KEY=my_key
OPENEDX_AWS_SECRET_ACCESS_KEY_my_secret
S3_REGION=ap-southeast-1
S3_USE_SSL=false
S3_STORAGE_BUCKET={my_bucket_name}
```
Note that we are not setting `S3_ADDRESSING_STYLE`.
Could you please try and confirm that the issue with ORA2 URL is resolved?

**Comment by fghaas** [comment]
@vunguyen-dmt Just a quick reminder that we're still waiting for your feedback here. We'd like to make sure that this issue is resolved, ahead of cutting a new point release. 

You can test like this, in your Tutor environment:

```bash
pip install git+https://github.com/hastexo/tutor-contrib-s3@main
tutor plugins enable s3
tutor config save
```

... and then you can run `tutor local restart openedx` to pick up the changes.

**Comment by foadlind** [comment]
I assume this is resolved and close the issue.
