### ISSUE TITLE
commit 54ce848a006a666ef9e7ecc57d91189e32ed7375 has breaking changes

### ISSUE THREAD

**Issue by lpm0073** [hastexo/tutor-contrib-s3#30]
# Summary

if you don't set S3_CUSTOM_DOMAIN then this commit causes the domain to revert to the edx default of edxuploads.s3.amazonaws.com. see https://github.com/openedx/edx-platform/blob/master/lms/envs/production.py#L460

Just a guess, but you might want to default S3_CUSTOM_DOMAIN to S3_STORAGE_BUCKET.

## What I did

re-running my automated deployment scripts broke the AWS S3 integration.

## My environment

    - name: Install S3 plugin
        run: |-
          pip install git+https://github.com/hastexo/tutor-contrib-s3@main
          tutor plugins enable s3

          $(kubectl get secret s3-openedx-storage -n $NAMESPACE  -o json | jq  '.data | map_values(@base64d)' | jq -r 'keys[] as $k | "export \($k|ascii_upcase)=\(.[$k])"' )
          tutor config save --set OPENEDX_AWS_ACCESS_KEY="$OPENEDX_AWS_ACCESS_KEY" \
                            --set OPENEDX_AWS_SECRET_ACCESS_KEY="$OPENEDX_AWS_SECRET_ACCESS_KEY" \
                            --set S3_STORAGE_BUCKET="$S3_STORAGE_BUCKET" \
                            --set OPENEDX_AWS_QUERYSTRING_AUTH="False" \
                            --set OPENEDX_AWS_S3_SECURE_URLS="False" \
                            --set S3_REGION="us-east-2"

## Additional context

adding S3_CUSTOM_DOMAIN fixes the problem, assuming that you actually have a custom domain.

    - name: Install S3 plugin
        run: |-
          pip install git+https://github.com/hastexo/tutor-contrib-s3@main
          tutor plugins enable s3

          $(kubectl get secret s3-openedx-storage -n $NAMESPACE  -o json | jq  '.data | map_values(@base64d)' | jq -r 'keys[] as $k | "export \($k|ascii_upcase)=\(.[$k])"' )
          tutor config save --set OPENEDX_AWS_ACCESS_KEY="$OPENEDX_AWS_ACCESS_KEY" \
                            --set OPENEDX_AWS_SECRET_ACCESS_KEY="$OPENEDX_AWS_SECRET_ACCESS_KEY" \
                            --set S3_STORAGE_BUCKET="$S3_STORAGE_BUCKET" \
                            --set S3_CUSTOM_DOMAIN="cdn-web.stepwisemath.ai" \
                            --set OPENEDX_AWS_QUERYSTRING_AUTH="False" \
                            --set OPENEDX_AWS_S3_SECURE_URLS="False" \
                            --set S3_REGION="us-east-2"

**Comment by fghaas** [comment]
Adding a mention of #29 here (which included the problematic commit), so that we get a back-reference on the PR.

**Comment by foadlind** [comment]
@fghaas I'll prepare a PR

**Comment by fghaas** [comment]
@lpm0073: With the latest fix from @foadlind (#31), would you mind giving the current state of `main` another spin?

**Comment by lpm0073** [comment]
i will. it will be later today.
