### ISSUE TITLE
Ready to release v0.1.2?

### ISSUE THREAD

**Issue by lpm0073** [hastexo/tutor-contrib-s3#32]
# Summary

Good news to report: All features appear to be working stably. It'd be great if you could tag the present state as v0.1.2 so that i can move my CI workflow off of your main branch.

thanks!! :D

**Comment by fghaas** [comment]
Thanks for the feedback! It's not 0.1.2 but 0.2.0 (new feature means [SemVer](https://semver.org/) calls for new minor, not new point release): fixed in #33.
