### ISSUE TITLE
[Feature] Disable / Enable profile pictures to use AWS S3

### ISSUE THREAD

**Issue by erickhgm** [hastexo/tutor-contrib-s3#40]
## :point_up: Feature
Ability to **disable / enable** profile pictures to use AWS S3.

## Motivation
The **Open edX** functionality for managing AWS S3 storage comes directly from [Django](https://www.djangoproject.com/) and it’s actually quite simple to read and understand: [Amazon S3 — django storages](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html). 

Many different kinds of user data get stored, including user `Profile Pictures`, `Grades`, `Reports`, and auxiliary course content like `PDF documents` / `Video` files used in `ORA2` (Open Response Assessment).

Additionally, each of these different kinds of data can be individually configured, if you want. And so using AWS S3 is not an all-or-none decision. Furthermore, if you want, you can store different kinds of user data in different S3 buckets or filesystem paths.

**Personal motivation**: In my user case, all users authenticate using a 3rd party authentication provider and our template does not allow users to modify their profile pictures. If we decide to use it in the future, we will not use Open edX way to do it as we have security rules that do not allow user data to be publicly exposed without a secure assign URL.

## Expected Behavior
Add the `S3_PROFILE_IMAGE_ENABLE` property to be able to **disable / enable** these files from being stored on S3.
So the default Tutor setting won't be overwrite and will be used.
```
PROFILE_IMAGE_BACKEND["options"]["location"] = os.path.join(
    MEDIA_ROOT, "profile-images/"
)
```

## Current Behavior
If we enable the plugin the profile pictures is always set to be store in S3.
`openedx-lms-common-settings` content:
```
PROFILE_IMAGE_BACKEND = {
    "class": DEFAULT_FILE_STORAGE,
    "options": {
        "bucket": "{{ S3_PROFILE_IMAGE_BUCKET }}",
        "location": PROFILE_IMAGE_BACKEND["options"]["location"].lstrip("/"),
        {% if S3_PROFILE_IMAGE_CUSTOM_DOMAIN %}"custom_domain": "{{ S3_PROFILE_IMAGE_CUSTOM_DOMAIN }}",{% endif %}
    },
}
```

## :bulb: Possible solutions
Add a condition to set the profile pictures setting or not using the `S3_PROFILE_IMAGE_ENABLE` property.
`openedx-lms-common-settings` content:
```
{% if S3_PROFILE_IMAGE_ENABLE %}
PROFILE_IMAGE_BACKEND = {
    "class": DEFAULT_FILE_STORAGE,
    "options": {
        "bucket": "{{ S3_PROFILE_IMAGE_BUCKET }}",
        "location": PROFILE_IMAGE_BACKEND["options"]["location"].lstrip("/"),
        {% if S3_PROFILE_IMAGE_CUSTOM_DOMAIN %}"custom_domain": "{{ S3_PROFILE_IMAGE_CUSTOM_DOMAIN }}",{% endif %}
    },
}
{% endif %}
```

## Context
* Open edX release: open-release/maple.2
* Tutor version: 13.1.8
* Tutor S3 plugin version: 0.2.1

**Comment by foadlind** [comment]
Hi @erickhgm,

I think this is a good feature suggestion. However I would suggest an alternative solution: We set `S3_PROFILE_IMAGE_BUCKET` to be empty by default. And only override `PROFILE_IMAGE_BACKEND` if a bucket is specified.

### Motivation:
Currently, [by default](https://github.com/hastexo/tutor-contrib-s3/blob/2b9b22e78a578fb4d7b5d887b0529d462310c775/tutors3/plugin.py#L18), we set `S3_PROFILE_IMAGE_BUCKET` to be the same as `S3_STORAGE_BUCKET`. 
However, as stated in the [docs](https://github.com/hastexo/tutor-contrib-s3/blob/2b9b22e78a578fb4d7b5d887b0529d462310c775/README.md?plain=1#L56), `S3_PROFILE_IMAGE_BUCKET` *must* have a public ACL if signature version `s3v4` is used. 
As `s3v4` *is* the [default signature version](https://github.com/hastexo/tutor-contrib-s3/blob/2b9b22e78a578fb4d7b5d887b0529d462310c775/tutors3/plugin.py#L23), we should not set `S3_PROFILE_IMAGE_BUCKET` to be the same as `S3_STORAGE_BUCKET` by default, as that one usually does not have a public ACL. We should instead set `S3_PROFILE_IMAGE_BUCKET` to be an empty string. 

This way we provide defaults that are in alignment with the docs, and we enable the use-case that @erickhgm mentioned by checking for a non-empty profile image bucket name before overriding the profile image backend.

@fghaas what do you think?

**Comment by fghaas** [comment]
Yes that sounds like a reasonable approach.

One caveat: I don't know off the top of my head right now what the implications of using the default `MEDIA_ROOT` folder are under those circumstances, but I seem to recall that it means when profile images are uploaded, they just live in the container's filesystem (and not in a volume, or some such). If that recollection is correct, then it would mean profile images are being wiped whenever a container is thrown away and recreated — which is a very frequent occurrence — and I don't know whether we really want to make it easy for users to do that. It would effectively make profile images *look* like they work (the user can upload one and see their profile page updated with it), but then they only last until the next time the container is recreated.

Again, that is if (a) my recollection is correct and (b) the behavior hasn't recently changed.

**Comment by erickhgm** [comment]
@foadlind I liked this alternative of just overwriting the `PROFILE_IMAGE_BACKEND` if `S3_PROFILE_IMAGE_BUCKET` is not empty.

A point that I thought with this approach is if we set `S3_PROFILE_IMAGE_BUCKET`default value to empty we will change the default behavior of the plugin when someone updates. But that seems correct, because as you said:  
> `S3_PROFILE_IMAGE_BUCKET` must have a public ACL to work and the default configuration doesn't offer this.

---

@fghaas I tested this situation before creating the issue. The default `MEDIA_ROOT` of Tutor is `"/openedx/media/"` and this path is a volume. So, just if the user changes the default `MEDIA_ROOT` location or changes de volume we will have the problem that you mentioned.

**Comment by erickhgm** [comment]
So joining the ideas, we would have:
```
{% if S3_PROFILE_IMAGE_BUCKET %}
PROFILE_IMAGE_BACKEND = {
    "class": DEFAULT_FILE_STORAGE,
    "options": {
        "bucket": "{{ S3_PROFILE_IMAGE_BUCKET }}",
        "location": PROFILE_IMAGE_BACKEND["options"]["location"].lstrip("/"),
        {% if S3_PROFILE_IMAGE_CUSTOM_DOMAIN %}"custom_domain": "{{ S3_PROFILE_IMAGE_CUSTOM_DOMAIN }}",{% endif %}
    },
}
{% endif %}
```

Use cases:
1. If `S3_PROFILE_IMAGE_BUCKET` is empty (default behavior) the images will be saved in `/openedx/media/profile-images/` path (tutor default config) that is inside a volume (also default tutor config). The `PROFILE_IMAGE_BACKEND` won't be overwritten.
2. If `S3_PROFILE_IMAGE_BUCKET` is set the images will be saved in an `S3 Bucket` that must have a public ACL. The `PROFILE_IMAGE_BACKEND` will be overwritten.

**Comment by foadlind** [comment]
I'll make a PR for this.

**Comment by erickhgm** [comment]
@foadlind If you don't mind I would like to do the PR.

**Comment by foadlind** [comment]
Sure! go ahead @erickhgm

**Comment by erickhgm** [comment]
Is the release process made by you? 
This part [here](https://github.com/hastexo/tutor-contrib-s3/blob/main/HACKING.md#how-to-cut-a-release)

**Comment by foadlind** [comment]
Yes we will cut a release when your PR is merged.
