### ISSUE TITLE
Course Management Studio - Files & Uploads is blank after installing plugin

### ISSUE THREAD

**Issue by lpm0073** [hastexo/tutor-contrib-s3#46]
# Summary

The Files & Uploads page in Course Management Studio is blank after installing plugin. This is happening on two platforms that I'm supporting. The tutor-contrib-s3 is used on both. The plugin otherwise works fine in all other parts of the platform. 

## What I did

Installed the plugin as follows:

         pip install git+https://github.com/hastexo/tutor-contrib-s3@v0.2.0
          tutor plugins enable s3
          tutor config save --set OPENEDX_AWS_ACCESS_KEY="$OPENEDX_AWS_ACCESS_KEY" \
                            --set OPENEDX_AWS_SECRET_ACCESS_KEY="$OPENEDX_AWS_SECRET_ACCESS_KEY" \
                            --set OPENEDX_AWS_QUERYSTRING_AUTH="False" \
                            --set OPENEDX_AWS_S3_SECURE_URLS="False" \
                            --set S3_STORAGE_BUCKET="$S3_STORAGE_BUCKET" \
                            --set S3_CUSTOM_DOMAIN="$S3_CUSTOM_DOMAIN" \
                            --set S3_REGION="$S3_REGION"

It’s OK to remove or mask credentials (like your `OPENEDX_AWS_*` settings), but otherwise try to err on the side of sharing more rather than less information.

## What I expected to happen

Was expecting to see the normal Files & Uploads page

Explain how you expected Tutor to behave with your configuration.

## What actually happened

The page looks like this instead:

<img width="957" alt="Screen Shot 2022-05-18 at 17 42 31" src="https://user-images.githubusercontent.com/1178819/169167720-6a255c8f-1b39-4f51-bad6-0d9a311432cf.png">

Explain how Tutor behaved differently than you expected.

## My environment

Tutor Maple.3 on Kubernetes 1.22. Additional details about the platform are available here: [https://github.com/academiacentral-org/openedx_devops](https://github.com/academiacentral-org/openedx_devops)

Please add some information about the environment that you’re working in. At a minimum, include these items:

* Tutor version: (Insert the Tutor version you are using.)
* `tutor-contrib-s3` version: (Insert the plugin version you are using. If you installed from Git, enter the tag or branch name, or the commit reference.)

Additionally, you might also want to add any of the items below, if you think they might be relevant to the bug:

* Kubernetes versions: 1.22output. Otherwise, remove this item.)
* Docker/Podman version: 
* Platform details:  AWS
* S3 implementation details: 

## Additional context

If there’s any other context you’d like to share, please add it here. Otherwise, you can delete this section.

**Comment by erickhgm** [comment]
Open the page with `Developer Tools` opened in the `Network` section and check if there are `js` and `css` files missing.

![image](https://user-images.githubusercontent.com/6977922/169168159-06fe1058-3d31-45b4-b0f1-ec26717ec700.png)

If you have this problem, the solution is update `studio-frontend` app: https://github.com/openedx/edx-platform/pull/30309

**Comment by lpm0073** [comment]
yes. Confirming that the same files in your screen shot actually. Does this mean that i need rebuild the openedx image in order to recompile static assets? 


<img width="841" alt="Screen Shot 2022-05-18 at 17 56 20" src="https://user-images.githubusercontent.com/1178819/169168569-42e242b8-abf2-4705-8aa7-d09069aeacde.png">

**Comment by erickhgm** [comment]
The last version of the tutor has the fix, [here](https://github.com/overhangio/tutor/blob/f6ecfd3e7440d1a86b0c61e218797ffeafb7b52c/tutor/templates/build/openedx/Dockerfile#L61).

Yes, update tutor. 
If you have patches in your Dockerfile, run `tutor images build openedx` and `tutor images push openedx`.

**Comment by lpm0073** [comment]
confirming that rebuilding the image with the latest version of tutor fixed the problem. Thanks @erickhgm !!!!!
