### ISSUE TITLE
Upload image in Discussion return wrong link.

### ISSUE THREAD

**Issue by vunguyen-dmt** [hastexo/tutor-contrib-s3#52]
In discussion, I created a post then clicked Image to upload an image.
The link returned is: https://s3.{region}.amazonaws.com/{bucket-name}/{image_name}
It should've been: https://{bucket-name}.s3.{region}.amazonaws.com...
![image](https://user-images.githubusercontent.com/34919039/174753869-7eb125a9-35ac-4201-94cc-9aaf2738ca69.png)

**Comment by foadlind** [comment]
@vunguyen-dmt please share your:
- `S3_*` settings from Tutor’s `config.yml`,
- Tutor version,
- and tutor-contrib-s3 version.

**Comment by vunguyen-dmt** [comment]
S3_REGION: ap-southeast-1
S3_STORAGE_BUCKET: {my-bucket}

I'm using Tutor v14.0.1
tutor-contrib-s3 I used code from this branch: https://github.com/lpm0073/tutor-contrib-s3/tree/tutor14
It worked for me when I upload files in [SGA](https://github.com/mitodl/edx-sga) or other tasks such as Download, Export,... But for uploading images in discussion post didn't work.

**Comment by fghaas** [comment]
Hi, sorry but we can't possibly handle issues here that were encountered using a fork. Please reproduce with the current `main` branch, and then please file a new issue using the _Bug Report_ issue template, making sure to fill the blanks in full. Thank you!
