### ISSUE TITLE
Images uploaded in discussion do not display, Staff Graded Assignment (SGA) still upload to local storage.

### ISSUE THREAD

**Issue by vunguyen-dmt** [hastexo/tutor-contrib-s3#53]
# Summary

1. When I upload an  image to a discussion post, the link returned is: https://s3.ap-southeast-1.amazonaws.com/{my_bucket_name}/{file_name}
I checked AWS S3 bucket and found the image was inserted. I think the image could not be displayed due to the link returned lacking URL params like X-Amz-Signature, X-Amz-Credential ...
I expected the image can be displayed without setting my bucket to public.

2.  When I upload a file in  SGA component the download link returned is https://{{LMS_HOST}}/courses/{COURSE_ID}/xblock/block-v1:test+1000+2021_T3+type@edx_sga+block@216fcd6feaad41d88b4b1b53f2ad570d/handler/download_assignment
which is a local link and can be downloaded.
I expected it returned a S3 link rather than a local link.

I use tutor v13.1.5 and tutor-contrib-s3 v0.2.2
My config.yml
OPENEDX_AWS_ACCESS_KEY: {my_access_key}
OPENEDX_AWS_SECRET_ACCESS_KEY: {my_secret_key}
S3_REGION: ap-southeast-1
S3_STORAGE_BUCKET: {my_bucket}

**Comment by fghaas** [comment]
@vunguyen-dmt What you are reporting here looks like two separate problems (one affecting the forum, one affecting edx-sga); can you please file one issue per problem in the future?

1. We don't deploy the discussion forum on our Open edX environments, and Tutor core does not touch it either. Its functionality comes from the [`tutor-forum` plugin](https://github.com/overhangio/tutor-forum), and I don't know how it's meant to use S3, or whether it supports that at all. If you have a Discourse thread or a `tutor-forum` issue discussing this, please link it here.
2. As for [edx-sga](https://github.com/mitodl/edx-sga), and it not using S3 storage as configured, please post your generated {{lms.env.json}} and settings module.

**Comment by vunguyen-dmt** [comment]
Sorry for adding multiple problems in one issue.
My lms.env.json look like this:
{
  "SITE_NAME": "lms.example.com",
  "BOOK_URL": "",
  "LOG_DIR": "/openedx/data/logs",
  "LOGGING_ENV": "sandbox",
  "OAUTH_OIDC_ISSUER": "https://lms.example.com/oauth2",
  "PLATFORM_NAME": "My Openedx",
  "FEATURES": {
    "ALLOW_PUBLIC_ACCOUNT_CREATION": false,
    "ENABLE_BULK_ENROLLMENT_VIEW": true,
    "ALLOW_AUTOMATED_SIGNUPS": true,
    "ALLOW_EMAIL_ADDRESS_CHANGE": false,
    "ENABLE_DASHBOARD_SEARCH": true,
    "HIDE_DASHBOARD_COURSES_UNTIL_ACTIVATED": true,
    "ENABLE_SPECIAL_EXAMS": true,
    "SHOW_HEADER_LANGUAGE_SELECTOR": true,
    "ENABLE_CHANGE_USER_PASSWORD_ADMIN": true,
    "CERTIFICATES_HTML_VIEW": true,
    "PREVIEW_LMS_BASE": "preview.lms.example.com",
    "ENABLE_CORS_HEADERS": true,
    "ENABLE_COURSE_DISCOVERY": true,
    "ENABLE_COURSEWARE_SEARCH": true,
    "ENABLE_CSMH_EXTENDED": false,
    "ENABLE_DASHBOARD_SEARCH":  true,
    "ENABLE_COMBINED_LOGIN_REGISTRATION": true,
    "ENABLE_GRADE_DOWNLOADS": true,
    "ENABLE_LEARNER_RECORDS": false,
    "ENABLE_MOBILE_REST_API": true,
    "ENABLE_OAUTH2_PROVIDER": true,
    "ENABLE_THIRD_PARTY_AUTH": true,
    "MILESTONES_APP": true,
    "ENABLE_PREREQUISITE_COURSES": true
  },
  "LMS_ROOT_URL": "https://lms.example.com",
  "CMS_ROOT_URL": "https://studio.lms.example.com",
  "CMS_BASE": "studio.lms.example.com",
  "LMS_BASE": "lms.example.com",
  "CONTACT_EMAIL": "no-reply@example.com",
  "CELERY_BROKER_TRANSPORT": "redis",
  "CELERY_BROKER_HOSTNAME": "redis:6379",
  "CELERY_BROKER_VHOST": "0",
  "CELERY_BROKER_USER": "",
  "CELERY_BROKER_PASSWORD": "",
  "ALTERNATE_WORKER_QUEUES": "cms",
  "ENABLE_COMPREHENSIVE_THEMING": true,
  "COMPREHENSIVE_THEME_DIRS": ["/openedx/themes"],
  "STATIC_ROOT_BASE": "/openedx/staticfiles",
  "EMAIL_BACKEND": "django.core.mail.backends.smtp.EmailBackend",
  "EMAIL_HOST": "smtp",
  "EMAIL_PORT": 8025,
  "EMAIL_USE_TLS": false,
  "ACE_ROUTING_KEY": "edx.lms.core.default",
  "HTTPS": "on",
  "LANGUAGE_CODE": "en",
  "SESSION_COOKIE_DOMAIN": "lms.example.com",
  "COMMENTS_SERVICE_URL": "http://forum:4567",
  "COMMENTS_SERVICE_KEY": "forumapikey",
  "AWS_ACCESS_KEY_ID": "{my_access_key}",
  "AWS_SECRET_ACCESS_KEY": "{my_secret_key}",
  "AWS_STORAGE_BUCKET_NAME": "{my_bucket}",
  "AWS_DEFAULT_ACL": null,
  "AWS_QUERYSTRING_AUTH": true,
  "DEFAULT_FILE_STORAGE": "storages.backends.s3boto3.S3Boto3Storage",
  "XBLOCK_FS_STORAGE_BUCKET": "{my_bucket}",
  "XBLOCK_FS_STORAGE_PREFIX": "xblock",
  "CACHES": {
    "default": {
      "KEY_PREFIX": "default",
      "VERSION": "1",
      "BACKEND": "django_redis.cache.RedisCache",
      "LOCATION": "redis://@redis:6379/1"
    },
    "general": {
root@atm:~/.local/share/tutor/env/apps/openedx/config#
      "BACKEND": "django_redis.cache.RedisCache",
      "LOCATION": "redis://@redis:6379/1"
    },
    "mongo_metadata_inheritance": {
      "KEY_PREFIX": "mongo_metadata_inheritance",
      "TIMEOUT": 300,
      "BACKEND": "django_redis.cache.RedisCache",
      "LOCATION": "redis://@redis:6379/1"
    },
    "staticfiles": {
      "KEY_PREFIX": "staticfiles_lms",
      "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
      "LOCATION": "staticfiles_lms"
    },
    "configuration": {
      "KEY_PREFIX": "configuration",
      "BACKEND": "django_redis.cache.RedisCache",
      "LOCATION": "redis://@redis:6379/1"
    },
    "celery": {
      "KEY_PREFIX":  "celery",
      "TIMEOUT": "7200",
      "BACKEND": "django_redis.cache.RedisCache",
      "LOCATION": "redis://@redis:6379/1"
    },
    "course_structure_cache": {
      "KEY_PREFIX": "course_structure",
      "TIMEOUT": "7200",
      "BACKEND": "django_redis.cache.RedisCache",
      "LOCATION": "redis://@redis:6379/1"
    },
    "ora2-storage": {
      "KEY_PREFIX":  "ora2-storage",
      "BACKEND": "django_redis.cache.RedisCache",
      "LOCATION": "redis://@redis:6379/1"
    }
  },
  "SECRET_KEY": "***",
  "CONTENTSTORE": null,
  "DOC_STORE_CONFIG": null,
  "AWS_STORAGE_BUCKET_NAME": "{my_bucket}",
  "AWS_S3_CUSTOM_DOMAIN": "",
  "AWS_QUERYSTRING_AUTH": true,
  "XQUEUE_INTERFACE": {
    "django_auth": null,
    "url": null
  },
  "DATABASES": {
    "default": {
      "ENGINE": "django.db.backends.mysql",
      "HOST": "mysql",
      "PORT": 3306,
      "NAME": "openedx",
      "USER": "openedx",
      "PASSWORD": "***",
      "ATOMIC_REQUESTS": true,
      "OPTIONS": {
        "init_command": "SET sql_mode='STRICT_TRANS_TABLES'"
      }
    }
  },
  "EMAIL_HOST_USER": "",
  "EMAIL_HOST_PASSWORD": ""
}
I will keep investigating the discussion forum issue.

**Comment by vunguyen-dmt** [comment]
SGA files are uploaded to S3, the download links made me think it was in local file system.
Discussion files are uploaded to s3 due to S3_STORAGE_BUCKET config. I can still make it work the way I want by using complex bucket pollicies but it would be nice to have a config for the bucket that is used by discussion posts.
