### ISSUE TITLE
Lilac version

### ISSUE THREAD

**Issue by erickhgm** [hastexo/tutor-contrib-s3#58]
# Summary

I'm working on a project where we are migrating an OpenedX instance (Lilac using the native installation method) to Tutor (keeping Lilac). After that, we will migrate the OpenedX version, Lilac -> Maple -> Nutmeg ...

My question is, would you accept a version of this plugin for lilac?

## What I expected to happen

My plan is to use this plugin while the migration process, Lilac -> Maple -> Nutmeg ... and don't set the S3 setting manually.

**Comment by fghaas** [comment]
@erickhgm Nope, sorry, we have no intention to support Lilac with this plugin. And I would strongly advise against using Tutor for Lilac; it only became the upstream-supported deployment method in Maple.
